CREATE TABLE USERTB (
	USERNAME VARCHAR2(20),
	PASSWORD VARCHAR2(500) NOT NULL,
	NAME VARCHAR2(100),
	PRIMARY KEY(USERNAME)
);

/*Username: Miguel, password: pass*/
INSERT INTO USERTB (USERNAME, PASSWORD, NAME) VALUES ('Miguel','$2a$10$2sZ/K/d9ZRMxqiQwfUJXoefMZyGZVOVgrnKGCR2NwmQN3FEYab3PW', '');
