CREATE TABLE USERTB (
	USERNAME VARCHAR2(20),
	PASSWORD VARCHAR2(500) NOT NULL,
	NAME VARCHAR2(100),
	PRIMARY KEY(USERNAME)
);

INSERT INTO USERTB (USERNAME, PASSWORD, NAME) VALUES ('Miguel','pass', 'Miguel Ángel');
